runtime: python
api_version: 1
threadsafe: true
env: flex

runtime_config:
  python_version: 3.6

handlers:
- url: /.*
  script: main.app

health_check:
  enable_health_check: True
  check_interval_sec: 15
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
